### ISSUE TITLE
broken versions range in sprockets-2.9.4.pom

### ISSUE THREAD

**Issue by mkristian** [jruby/rubygems-servlets#13]
http://rubygems-proxy.torquebox.org/releases/rubygems/sprockets/2.9.4/sprockets-2.9.4.pom

does not handle `!= 1.3.0` inside gemspec correctly

**Comment by rtyler** [comment]
Good catch by @raelik!

**Comment by raelik** [comment]
@mkristian I did some research on this, and it appears that the issue is really within torquebox/maven-tools, during POM generation, and may be in Maven::Tools::DSL.
