### ISSUE TITLE
Gems fail to download

### ISSUE THREAD

**Issue by matt-blanchette** [jruby/rubygems-servlets#14]
Requests for gems are redirected to AWS S3 returning 301 Moved Permanently.

For example, request for:
http://rubygems-proxy.torquebox.org/releases/rubygems/compass/1.0.3/compass-1.0.3.gem
is 302 redirecting to:
http://s3.amazonaws.com/production.s3.rubygems.org/gems/compass-1.0.3.gem

This S3 response includes error code "PermanentRedirect" with the message:
"The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint."

**Comment by matt-blanchette** [comment]
Looks like there is no Location header being returned from rubygems,
causing the failing redirect to S3.

**Comment by bbrowning** [comment]
Fixed in b20cbc597f8213b673241075c6357f8bbe7fb45a - thanks for the report!
