### ISSUE TITLE
Add "how to host private gems" to Readme

### ISSUE THREAD

**Issue by fapdash** [jruby/rubygems-servlets#15]
I tried to drop my .gem file into /target/hosted but it's not showing up at http://0.0.0.0:8989/hosted/.
It would be really helpful if you could add a paragraph describing how to add gems.

**Comment by mkristian** [comment]
right, I never added it as I never added tests for it. will find some time over the weekend.

**Comment by fapdash** [comment]
Thank you, I'm trying to use/serve a private/local gem in a gradle build with [jruby gradle plugin](https://github.com/jruby-gradle/jruby-gradle-plugin), if that matters.

**Comment by mkristian** [comment]
I guessed it already since I saw an issue from you on the gradle list - yes it is the right usecase. I just do not have too much extra time during the week (anymore)

**Comment by mkristian** [comment]
still pending . . .

**Comment by mkristian** [comment]
@fap- I did indeed to add some code to get the upload working - thanx for asking. could you check it out and test this on your side before I make a new release ?

**Comment by fapdash** [comment]
I pushed a gem with nexus.

```
gem nexus asciidoctor-pdf-1.5.0.alpha.14.hosted.gem 
[...]
Uploading gem to Nexus...
OK
```

Server saved it

```
[INFO] hosted: /gems/asciidoctor-pdf-1.5.0.alpha.14.hosted.gem - RubygemsFile[type=GEM, storage=/gems/a/asciidoctor-pdf-1.5.0.alpha.14.hosted.gem, remote=/gems/asciidoctor-pdf-1.5.0.alpha.14.hosted.gem, name=asciidoctor-pdf-1.5.0.alpha.14.hosted, state=PAYLOAD, payload=HttpInputOverHTTP@6d87243f[c=1389056,s=EOF]]
```

I can download the gem from
http://localhost:8989/hosted/gems/asciidoctor-pdf-1.5.0.alpha.14.hosted.gem
But there is no pom
http://localhost:8989/hosted/gems/asciidoctor-pdf-1.5.0.alpha.14.hosted.pom => 404

Using I tested this with jruby gradle base plugin 1.3.3 with their suggested config.

```
jruby {
    defaultRepositories false
}

repositories {
    maven { url 'http://localhost:8989/releases' }
}

dependencies {
    gems 'rubygems:asciidoctor-pdf:1.5.0.alpha.14.hosted'
}
```

```
Resource missing. [HTTP GET: http://localhost:8989/releases/rubygems/asciidoctor-pdf/1.5.0.alpha.14.hosted/asciidoctor-pdf-1.5.0.alpha.14.hosted.pom]
Resource missing. [HTTP HEAD: http://localhost:8989/releases/rubygems/asciidoctor-pdf/1.5.0.alpha.14.hosted/asciidoctor-pdf-1.5.0.alpha.14.hosted.jar]
```

Changing the maven endpoint to `/hosted` or `/merge` didn't work either.

Btw we got shown a way to use custom gems locally with the plugin [here](https://github.com/asciidoctor/asciidoctor-pdf/issues/650#issuecomment-258338060).
It's has the disadvantage that the dependencies have to be specified by hand but it works.
So if you are short on time and nobody else wants this feature I would suggest to maybe skip this feature for now? (assuming the fix is not trivial)

**Comment by mkristian** [comment]
`/hosted/maven/releases` is the right endpoint. will add this to the readme as well.

**Comment by fapdash** [comment]
This endpoint works! I had to activate the default repositories for jruby, so he would find the other dependencies.
